# Generated by Django 3.1.1 on 2020-11-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_auto_20201113_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default=0.000765076507650765, max_length=150),
            preserve_default=False,
        ),
    ]
