# Generated by Django 3.1.1 on 2020-11-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes/'),
        ),
    ]
